# generated by datamodel-codegen:
#   filename:  polls_value.json

from __future__ import annotations

from typing import Any
from typing import Dict
from typing import Union

from pydantic import BaseModel
from pydantic import Extra


class VoteWeightMethodItem(BaseModel):
    class Config:
        extra = Extra.forbid

    equal: Dict[str, Any]


class VoteWeightMethodItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    linear: Dict[str, Any]


class VoteWeightMethodItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    quadratic: Dict[str, Any]


class PollsValue(BaseModel):
    class Config:
        extra = Extra.forbid

    question: str
    description: str
    options: Dict[str, str]
    vote_weight_method: Union[
        VoteWeightMethodItem, VoteWeightMethodItem1, VoteWeightMethodItem2
    ]
    vote_period: str
    issuer: str
    timestamp: str
    level: str
    votes_count: Dict[str, str]
