# generated by datamodel-codegen:
#   filename:  votes_key.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class VotesKey(BaseModel):
    class Config:
        extra = Extra.forbid

    nat: str
    address: str
