# generated by datamodel-codegen:
#   filename:  votes_value.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class VotesValue(BaseModel):
    class Config:
        extra = Extra.forbid

    option: str
    weight: str
