# generated by datamodel-codegen:
#   filename:  governance_parameters_key.json

from __future__ import annotations

from pydantic import BaseModel


class GovernanceParametersKey(BaseModel):
    __root__: str
