# generated by datamodel-codegen:
#   filename:  governance_parameters_value.json

from __future__ import annotations

from typing import Any
from typing import Dict
from typing import Union

from pydantic import BaseModel
from pydantic import Extra


class VoteMethodItem(BaseModel):
    class Config:
        extra = Extra.forbid

    linear: Dict[str, Any]


class VoteMethodItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    quadratic: Dict[str, Any]


class GovernanceParametersValue(BaseModel):
    class Config:
        extra = Extra.forbid

    vote_method: Union[VoteMethodItem, VoteMethodItem1]
    vote_period: str
    wait_period: str
    escrow_amount: str
    escrow_return: str
    min_amount: str
    supermajority: str
    representatives_share: str
    representative_max_share: str
    quorum_update_period: str
    quorum_update: str
    quorum_max_change: str
    min_quorum: str
    max_quorum: str
