# generated by datamodel-codegen:
#   filename:  proposals_value.json

from __future__ import annotations

from typing import Any
from typing import Dict
from typing import List
from typing import Union

from pydantic import BaseModel
from pydantic import Extra


class KindItem(BaseModel):
    class Config:
        extra = Extra.forbid

    lambda_function: str


class KindItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    text: Dict[str, Any]


class TransferMutezItem(BaseModel):
    class Config:
        extra = Extra.forbid

    amount: str
    destination: str


class KindItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    transfer_mutez: List[TransferMutezItem]


class DistributionItem(BaseModel):
    class Config:
        extra = Extra.forbid

    amount: str
    destination: str


class TransferToken(BaseModel):
    class Config:
        extra = Extra.forbid

    fa2: str
    token_id: str
    distribution: List[DistributionItem]


class KindItem3(BaseModel):
    class Config:
        extra = Extra.forbid

    transfer_token: TransferToken


class StatusItem(BaseModel):
    class Config:
        extra = Extra.forbid

    approved: Dict[str, Any]


class StatusItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    cancelled: Dict[str, Any]


class StatusItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    executed: Dict[str, Any]


class StatusItem3(BaseModel):
    class Config:
        extra = Extra.forbid

    open: Dict[str, Any]


class StatusItem4(BaseModel):
    class Config:
        extra = Extra.forbid

    rejected: Dict[str, Any]


class TokenVotes(BaseModel):
    class Config:
        extra = Extra.forbid

    positive: str
    negative: str
    abstain: str
    total: str
    participation: str


class RepresentativesVotes(BaseModel):
    class Config:
        extra = Extra.forbid

    positive: str
    negative: str
    abstain: str
    total: str
    participation: str


class ProposalsValue(BaseModel):
    class Config:
        extra = Extra.forbid

    title: str
    description: str
    kind: Union[KindItem, KindItem1, KindItem2, KindItem3]
    issuer: str
    timestamp: str
    level: str
    quorum: str
    gp_index: str
    status: Union[
        StatusItem, StatusItem1, StatusItem2, StatusItem3, StatusItem4
    ]
    token_votes: TokenVotes
    representatives_votes: RepresentativesVotes
