# generated by datamodel-codegen:
#   filename:  representatives_votes_value.json

from __future__ import annotations

from typing import Any
from typing import Dict
from typing import Union

from pydantic import BaseModel
from pydantic import Extra


class RepresentativesVotesValueItem(BaseModel):
    class Config:
        extra = Extra.forbid

    abstain: Dict[str, Any]


class RepresentativesVotesValueItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    no: Dict[str, Any]


class RepresentativesVotesValueItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    yes: Dict[str, Any]


class RepresentativesVotesValue(BaseModel):
    __root__: Union[
        RepresentativesVotesValueItem,
        RepresentativesVotesValueItem1,
        RepresentativesVotesValueItem2,
    ]
