# generated by datamodel-codegen:
#   filename:  representatives_votes_key.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class RepresentativesVotesKey(BaseModel):
    class Config:
        extra = Extra.forbid

    nat: str
    string: str
