# generated by datamodel-codegen:
#   filename:  token_votes_key.json

from __future__ import annotations

from pydantic import BaseModel
from pydantic import Extra


class TokenVotesKey(BaseModel):
    class Config:
        extra = Extra.forbid

    nat: str
    address: str
