# generated by datamodel-codegen:
#   filename:  token_votes_value.json

from __future__ import annotations

from typing import Any
from typing import Dict
from typing import Union

from pydantic import BaseModel
from pydantic import Extra


class VoteItem(BaseModel):
    class Config:
        extra = Extra.forbid

    abstain: Dict[str, Any]


class VoteItem1(BaseModel):
    class Config:
        extra = Extra.forbid

    no: Dict[str, Any]


class VoteItem2(BaseModel):
    class Config:
        extra = Extra.forbid

    yes: Dict[str, Any]


class TokenVotesValue(BaseModel):
    class Config:
        extra = Extra.forbid

    vote: Union[VoteItem, VoteItem1, VoteItem2]
    weight: str
