# To refresh existing project run `dipdup init --base --force` after modifying this file.
# To generate a new project from this replay run `dipdup new --replay <path_to_file>`.
#
spec_version: 2.0
replay:
  dipdup_version: 7
  template: demo_blank
  package: dao_indexer
  version: 0.0.1
  description: Teia DAO indexer built with DipDup
  license: MIT
  name: Javier Gracia Carpio
  email: jagracar@gmail.com
  postgres_image: postgres:15
  postgres_data_path: /var/lib/postgresql/data
  hasura_image: hasura/graphql-engine:latest
  line_length: 80
